### ISSUE TITLE
footer 컴포넌트 수정

### ISSUE THREAD

**Issue by nohgijin** [woowa-techcamp-2020/bmart-8#74]
## 설명 
footer 고정되도록 수정
footer 아래 간격 삭제

## 체크리스트
- [x] 고정되도록 수정
- [x] 아래 간격 삭제

**Comment by atobaum** [comment]
지금 dev 브랜치에서 푸터 너비도 이상해요
<img width="408" alt="image" src="https://user-images.githubusercontent.com/8086328/90732104-90172900-e305-11ea-9125-0b3cfcf0b31f.png">

**Comment by atobaum** [comment]
dev에서 캐로셀도 사라졌는데 그것도 고쳐주실 수 있나요? 왠지 모르겠는데 저 밑에 가있어요..

**Comment by nohgijin** [comment]
넹 수정해볼게용~_~

**Comment by atobaum** [comment]
> 넹 수정해볼게용~_~

감사합니다.
